name: 'Github Release'
author: 'Lars Gohr'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
description: 'Publish Github releases from an action'
env:
  GITHUB_TOKEN: 'The Github Token'
inputs:
  release:
    description: 'The name of the release to publish'
    required: true
args: ['The release name']
runs:
  using: 'docker'
  image: 'Dockerfile'
- name: Github Release
  uses: elgohr/Github-Release-Action@v3.1
